<?php

namespace Proxies\__CG__\PD\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \PD\AppBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'apellidos', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'username', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'salt', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'direccion', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'fechaAlta', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'fechaNacimiento', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'dui', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'tipoUsuario', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'estado', 'supervisor', 'supervisados', 'vendedores');
        }

        return array('__isInitialized__', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'nombre', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'apellidos', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'username', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'salt', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'direccion', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'fechaAlta', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'fechaNacimiento', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'dui', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'tipoUsuario', '' . "\0" . 'PD\\AppBundle\\Entity\\Usuario' . "\0" . 'estado', 'supervisor', 'supervisados', 'vendedores');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreApellidos', array());

        return parent::getNombreApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', array($fechaAlta));

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', array());

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento($fechaNacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', array($fechaNacimiento));

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', array());

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDui($dui)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDui', array($dui));

        return parent::setDui($dui);
    }

    /**
     * {@inheritDoc}
     */
    public function getDui()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDui', array());

        return parent::getDui();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoUsuario($tipoUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoUsuario', array($tipoUsuario));

        return parent::setTipoUsuario($tipoUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoUsuario', array());

        return parent::getTipoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupervisor(\PD\AppBundle\Entity\Usuario $supervisor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupervisor', array($supervisor));

        return parent::setSupervisor($supervisor);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupervisor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupervisor', array());

        return parent::getSupervisor();
    }

    /**
     * {@inheritDoc}
     */
    public function addSupervisado(\PD\AppBundle\Entity\Usuario $supervisados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSupervisado', array($supervisados));

        return parent::addSupervisado($supervisados);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSupervisado(\PD\AppBundle\Entity\Usuario $supervisados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSupervisado', array($supervisados));

        return parent::removeSupervisado($supervisados);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupervisados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupervisados', array());

        return parent::getSupervisados();
    }

    /**
     * {@inheritDoc}
     */
    public function addVendedor(\PD\AppBundle\Entity\Libreta $libretas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVendedor', array($libretas));

        return parent::addVendedor($libretas);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVendedor(\PD\AppBundle\Entity\Libreta $libretas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVendedor', array($libretas));

        return parent::removeVendedor($libretas);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendedores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendedores', array());

        return parent::getVendedores();
    }

}
