<?php

namespace Proxies\__CG__\PD\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Libreta extends \PD\AppBundle\Entity\Libreta implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PD\\AppBundle\\Entity\\Libreta' . "\0" . 'id', 'caja', '' . "\0" . 'PD\\AppBundle\\Entity\\Libreta' . "\0" . 'correlativo', 'vendedor', 'precio_al_vendedor', 'precio_acumulado', 'premio_acumulado', 'raspable_gratis_acumulado', 'fecha_asignacion_vendedor', 'fecha_estado_final', 'tickets');
        }

        return array('__isInitialized__', '' . "\0" . 'PD\\AppBundle\\Entity\\Libreta' . "\0" . 'id', 'caja', '' . "\0" . 'PD\\AppBundle\\Entity\\Libreta' . "\0" . 'correlativo', 'vendedor', 'precio_al_vendedor', 'precio_acumulado', 'premio_acumulado', 'raspable_gratis_acumulado', 'fecha_asignacion_vendedor', 'fecha_estado_final', 'tickets');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Libreta $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrelativo($correlativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrelativo', array($correlativo));

        return parent::setCorrelativo($correlativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrelativo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrelativo', array());

        return parent::getCorrelativo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioAlVendedor($precioAlVendedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioAlVendedor', array($precioAlVendedor));

        return parent::setPrecioAlVendedor($precioAlVendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioAlVendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioAlVendedor', array());

        return parent::getPrecioAlVendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioAcumulado($precioAcumulado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioAcumulado', array($precioAcumulado));

        return parent::setPrecioAcumulado($precioAcumulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioAcumulado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioAcumulado', array());

        return parent::getPrecioAcumulado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAsignacionVendedor($fechaAsignacionVendedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAsignacionVendedor', array($fechaAsignacionVendedor));

        return parent::setFechaAsignacionVendedor($fechaAsignacionVendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAsignacionVendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAsignacionVendedor', array());

        return parent::getFechaAsignacionVendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaEstadoFinal($fechaEstadoFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaEstadoFinal', array($fechaEstadoFinal));

        return parent::setFechaEstadoFinal($fechaEstadoFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEstadoFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEstadoFinal', array());

        return parent::getFechaEstadoFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendedor(\PD\AppBundle\Entity\Usuario $vendedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendedor', array($vendedor));

        return parent::setVendedor($vendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendedor', array());

        return parent::getVendedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaja(\PD\AppBundle\Entity\Caja $caja = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaja', array($caja));

        return parent::setCaja($caja);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaja', array());

        return parent::getCaja();
    }

    /**
     * {@inheritDoc}
     */
    public function addTicket(\PD\AppBundle\Entity\Ticket $tickets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTicket', array($tickets));

        return parent::addTicket($tickets);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTicket(\PD\AppBundle\Entity\Ticket $tickets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTicket', array($tickets));

        return parent::removeTicket($tickets);
    }

    /**
     * {@inheritDoc}
     */
    public function getTickets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTickets', array());

        return parent::getTickets();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremioAcumulado($premioAcumulado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremioAcumulado', array($premioAcumulado));

        return parent::setPremioAcumulado($premioAcumulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremioAcumulado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremioAcumulado', array());

        return parent::getPremioAcumulado();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaspableGratisAcumulado($raspableGratisAcumulado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaspableGratisAcumulado', array($raspableGratisAcumulado));

        return parent::setRaspableGratisAcumulado($raspableGratisAcumulado);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaspableGratisAcumulado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaspableGratisAcumulado', array());

        return parent::getRaspableGratisAcumulado();
    }

}
